kind: StorageClass
apiVersion: storage.aks.io/v1
metadata:
  name: azurediskaks
  namespace: ingress-basic
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete   # Retain or Delete
volumeBindingMode: Immediate   # WaitForFirstConsumer or Immediate
allowVolumeExpansion: true    # true or false
parameters:
  storageaccounttype: Standard_LRS   # Premium or Standard
  kind: Managed