#https://cert-manager.io/docs/tutorials/getting-started-aks-letsencrypt/

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: abdulnaser.alhamdy@yahoo.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: 37c05aa5-7335-4ed0-a600-dd4247abad87
            resourceGroupName: rg-aks
            hostedZoneName: elpatrontitan.com
            environment: AzurePublicCloud
            managedIdentity:
              clientID: e552c208-942d-49ac-9d91-d0f28beb65c5
      # - http01:
      #     ingress:
      #       # class: nginx
      #       class: azure-application-gateway