name: 'aks Destroy'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: aks
      run: terraform init

    - name: Terraform Destroy
      working-directory: aks
      run: terraform destroy -auto-approve

    - name: Delete rg-aks
      run: |
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
        az group delete --name rg-aks --yes --no-wait

    - name: Remove Terraform output file
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git rm -f tf-outputs.env || true
        git commit -m "Remove tf outputs after destroy" || true
        git push