name: 'AKS Deployment'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: aks
      run: terraform init
           
    - name: Terraform Format
      working-directory: aks
      run: terraform fmt

    - name: Terraform Plan
      working-directory: aks
      run: terraform plan
    
    - name: Terraform Apply
      working-directory: aks
      run: terraform apply -auto-approve

    - name: Commit and Push Terraform State
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add aks/terraform.tfstate
        git commit -m "Update Terraform state"
        git push